const PCOSResult = require("../models/PCOSResult");
const calculatePCOSScore = require("../utils/calculatePCOSScore");

/* 1️⃣ Submit PCOS Test + Auto Redirect */
exports.submitPCOSTest = async (req, res) => {
  try {
    console.log("PCOS API HIT");
    
    const answers = req.body;
    const score = calculatePCOSScore(answers);
    const percentage = Math.round((score / 100) * 100);
    const riskLevel = score >= 70 ? "High Risk" : score >= 40 ? "Moderate Risk" : "Low Risk";

    const result = await PCOSResult.create({
      userId: req.user?.id || "000000000000000000000001",
      score,
      percentage,
      riskLevel,
      answers
    });

    console.log("PCOS result saved:", result);

    res.json({
      success: true,
      data: result
    });
  } catch (err) {
    console.error("PCOS Test Error:", err);
    res.status(500).json({ 
      success: false,
      error: err.message 
    });
  }
};

/* 2️⃣ Dashboard PCOS Insights */
exports.getDashboardInsights = async (req, res) => {
  const result = await PCOSResult
    .findOne({ userId: req.user.id })
    .sort({ createdAt: -1 });

  res.json(result);
};

/* 3️⃣ Download PCOS PDF */
exports.downloadPCOSReport = async (req, res) => {
  const result = await PCOSResult
    .findOne({ userId: req.user.id })
    .sort({ createdAt: -1 });

  const doc = new PDFDocument();

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", "attachment; filename=PCOS_Report.pdf");

  doc.pipe(res);

  doc.fontSize(20).text("PCOS Health Report", { align: "center" });
  doc.moveDown();
  doc.fontSize(12).text(`Risk Level: ${result.riskLevel}`);
  doc.text(`Score: ${result.score}/100`);
  doc.moveDown();

  doc.text("Reported Symptoms:");
  Object.keys(result.answers).forEach(key => {
    if (result.answers[key]) doc.text(`• ${key}`);
  });

  doc.moveDown();
  doc.text("Generated by SwasthyaSuraksha AI");

  doc.end();
};

/* 4️⃣ Doctor Ready Summary */
exports.getDoctorSummary = async (req, res) => {
  const result = await PCOSResult
    .findOne({ userId: req.user.id })
    .sort({ createdAt: -1 });

  res.json(result);
};
